# 線形代数のサンプル
詳解ディープラーニング　Tensorflow・Kerasによる時系列データ処理　の１章

## ベクトル
NumpyのNdarrayクラス　np.array()
shapeすると３行１？→自動的にベクトルと解釈してくれる

In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)
print(a.shape)

[1 2 3]
[4 5 6]
(3,)


In [2]:
#２行３列の行列でshapeを確認してみる
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## ベクトルとベクトルの演算

In [3]:
#和
print(a + b)

[5 7 9]


In [4]:
#要素席　各要素を掛け算
print(a * b)

[ 4 10 18]


In [5]:
#内積　各要素を掛け算して足し合わせる→スカラー（数字）になる
print(np.dot(a,b))

32


### 素のPythonリストでやった場合
→ベクトルとしての計算ができない

In [6]:
a_list = [1, 2, 3]
b_list = [4, 5, 6]
print(a_list)
print(b_list)

[1, 2, 3]
[4, 5, 6]


In [7]:
print(a_list + b_list)

[1, 2, 3, 4, 5, 6]


In [8]:
print(a_list * b_list)
#→エラー

TypeError: can't multiply sequence by non-int of type 'list'

## 行列

In [9]:
#2行３列　行列
#さっき定義したc
print(c)

[[1 2 3]
 [4 5 6]]


In [10]:
#もう一つ２行３列
d = np.array([[2,2,2],[1,1,1]])
print(d)
print(d.shape)

[[2 2 2]
 [1 1 1]]
(2, 3)


## 行列の演算

In [11]:
#和
print(c + d)

[[3 4 5]
 [5 6 7]]


In [12]:
#要素積
print(c * d)

[[2 4 6]
 [4 5 6]]


In [13]:
#内積
print(np.dot(c,d))
#→エラーになる　内積は  ○行■列　と　■行○列　で数字を合わせる必要があるため

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [14]:
#cの行列を転地する　→　３行２列になる
print(c.T)
print((c.T).shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [15]:
#転置した行列を使って内積
print(np.dot(c.T, d))
#３行２列・２行３列　→　３行３列になる（外側の数字が残る）

[[ 6  6  6]
 [ 9  9  9]
 [12 12 12]]
